### ISSUE TITLE
Release LiFT-HRA dataset on Hugging Face

### ISSUE THREAD

**Issue by NielsRogge** [CodeGoat24/LiFT#1]
Hello @CodeGoat24 🤗 

I'm Niels and work as part of the open-source team at Hugging Face. I discovered your work through Hugging Face's daily papers as yours got featured: https://huggingface.co/papers/2412.04814.
The paper page lets people discuss about your paper and lets them find artifacts about it (your dataset for instance),
you can also claim the paper as yours which will show up on your public profile at HF.

It's great to see the LiFT-Critic and CogVideoX-2B-LiFT models already on the 🤗 hub! To further enhance discoverability and facilitate broader use, it would be beneficial to also host the LiFT-HRA dataset on Hugging Face.

Would you consider uploading the LiFT-HRA dataset to https://huggingface.co/datasets?  Hosting it there will provide several advantages:

* **Improved discoverability:** Researchers can easily find and utilize your dataset using the Hugging Face Datasets library:
```python
from datasets import load_dataset

dataset = load_dataset("your-hf-org-or-username/LiFT-HRA")
```
* **Enhanced visibility:** Increased visibility through Hugging Face's community and search features.
* **Dataset viewer:** The Hugging Face dataset viewer allows for an interactive exploration of your data directly in the browser.

If you're interested, we can provide guidance on the uploading process: https://huggingface.co/docs/datasets/loading.  We also support WebDataset, which is particularly useful for large datasets or datasets with various modalities: https://huggingface.co/docs/datasets/en/loading#webdataset

Let me know if you're interested or have any questions!

Cheers,
Niels
ML Engineer @ HF 🤗

**Comment by CodeGoat24** [comment]
Thank you very much for your support. Our team is continuing to annotate and clean the data. Once the dataset is finalized, we will upload it.

**Comment by FuNian788** [comment]
look forward to seeing your dataset

**Comment by CodeGoat24** [comment]
Thanks! Our LiFT-HRA dataset is coming soon!!

**Comment by NielsRogge** [comment]
Also opened a PR to link the LiFT models to the paper page: https://huggingface.co/Fudan-FUXI/LiFT-Critic-13b-lora/discussions/1.

**Comment by CodeGoat24** [comment]
We have released our proposed [LiFT-HRA](https://huggingface.co/collections/Fudan-FUXI/lift-hra-6760f063b04baaf6350c9d2e) dataset today!!
